Repository kowainik/trial, pull requests merged in 2020-06, with the labels that each got.

#58 [#56] prettyTrialWith function
  trial-example/app-advanced/Main.hs
  trial-example/app/Main.hs
  trial/src/Trial.hs
Labels: pretty-print

#59 [#46] Add 'fiascoOnEmpty'
  trial/src/Trial.hs
Labels: core, enhancement

#60 [#57] Add Trial combinators
  trial/src/Trial.hs
Labels: core, enhancement

#61 [#54] Add `taggedTrialListCodec`
  trial-tomland/src/Trial/Tomland.hs
Labels: TOML
