Repository kowainik/trial, pull requests merged in 2020-05, with the labels that each got.

#1 Initial Trial introduction
  app/Main.hs
  options.toml
  src/Trial.hs
  trial.cabal
Labels: idea :bulb:

#11 [#2] Add more instances to Trial
  src/Trial.hs
Labels: core

#10 [#6] Add laws property tests
  test/Spec.hs
  test/Test/Trial/Gen.hs
  test/Test/Trial/Laws.hs
  trial.cabal
Labels: tests

#12 [#3] Add notion of Fatality level to `e` part of Trial
  app/Main.hs
  src/Trial.hs
  test/Test/Trial/Gen.hs
Labels: idea :bulb:

#16 [#5] Add 'trialToEither' and 'eitherToTrial' functions
  src/Trial.hs
Labels: enhancement

#18 [#13] Track the source `Result` comes from
  app/Main.hs
  src/Trial.hs
Labels: enhancement

#19 Introduce TaggedTrial
  app/Main.hs
  src/Trial.hs
Labels: enhancement, refactoring

#20 [#9] Implement all functions in all instances
  src/Trial.hs
Labels: core, enhancement

#22 [#8] Use DList instead of list in Trial
  app/Main.hs
  src/Trial.hs
  test/Test/Trial/Gen.hs
  trial.cabal
Labels: enhancement

#24 [#14] Add smart constructors
  app/Main.hs
  src/Trial.hs
Labels: enhancement

#26 [#15] Hide internal details of 'Fatality' and provide uni-directional PatternSynonyms
  src/Trial.hs
  test/Test/Trial/Gen.hs
Labels: enhancement

#23 [#17] Add doctest
  .github/workflows/ci.yml
  src/Trial.hs
  test/Doctest.hs
  trial.cabal
Labels: documentation, tests

#28 [#27] toTrial and fromTrial properties
  test/Spec.hs
  test/Test/Trial/Gen.hs
  test/Test/Trial/Laws.hs
  test/Test/Trial/Property.hs
  trial.cabal
Labels: tests

#30 [#25] Functions to convert DList to List at the end
  src/Trial.hs
  test/Doctest.hs
Labels: core, enhancement

#31 Convert Trial to multi-package project
  .github/workflows/ci.yml
  cabal.project
  trial/CHANGELOG.md
  trial/LICENSE
  trial/app/Main.hs
  trial/options.toml
  trial/src/Trial.hs
  trial/test/Doctest.hs
  trial/test/Spec.hs
  trial/test/Test/Trial/Gen.hs
  trial/test/Test/Trial/Laws.hs
  trial/test/Test/Trial/Property.hs
  trial/trial.cabal
Labels: refactoring

#34 [#7] Add pretty printing functions
  trial-example/app/Main.hs
  trial/src/Trial.hs
  trial/trial.cabal
Labels: pretty-print

#38 [#37] Functor and Applicative correspondence law tests
  trial/test/Test/Trial/Laws.hs
Labels: tests

#39 [#4] Add juicy documentation
  README.md
Labels: documentation

#35 [#4] Write Haddock
  trial/README.md
  trial/src/Trial.hs
  trial/trial.cabal
Labels: documentation

#40 [#36] Support GHC-8.10
  .github/workflows/ci.yml
  trial-example/trial-example.cabal
  trial-optparse-applicative/trial-optparse-applicative.cabal
  trial-tomland/trial-tomland.cabal
  trial/trial.cabal
Labels: CI

#41 [#29] Property tests for Trial Fatality invariant check
  trial/src/Trial.hs
  trial/test/Test/Trial/Gen.hs
  trial/test/Test/Trial/Property.hs
Labels: tests

#43 [#42] Add Partial data type and type family for config with Trial
  README.md
  trial-example/app-advanced/Main.hs
  trial-example/trial-example.cabal
  trial/src/Trial.hs
Labels: enhancement

#48 [#47] Add trialParser to optparse-applicative package
  trial-optparse-applicative/src/Trial/OptparseApplicative.hs
  trial/trial.cabal
Labels: CLI

#51 [#50] Change Alternative instance
  README.md
  trial/src/Trial.hs
  trial/test/Test/Trial/Laws.hs
  trial/test/Test/Trial/Property.hs
Labels: core

#53 [#49] Add more COMPLETE pattern groups
  .github/workflows/ci.yml
  trial/src/Trial.hs
Labels: CI, core
